apiVersion: v1
kind: Service
metadata:
  name: my-security-app-service
spec:
  selector:
    app: my-security-app
  ports:
    - protocol: TCP
      port: 80 # Port your service exposes
      targetPort: 80 # Port your container listens on
  type: ClusterIP # Expose the service internally
